### ISSUE TITLE
Adding chapters to mp3 file

### ISSUE THREAD

**Issue by sebastiangelotte** [trevligmjukvara/production-scripts#1]
We should add chapter meta data to the mp3 file to enable time stamp hopping in supported podcast players.

The optimal solution I think would be to generate the chapters meta data with the production script, based on the exported label-track file from audacity.

---

Spec for chapters: https://id3.org/id3v2-chapters-1.0
Python cli for editing ID3 meta data: https://github.com/nicfit/eyeD3
Label track exported from Audacity: [label-track-exported-from-audacity.txt](https://github.com/trevligmjukvara/production-scripts/files/4535256/label-track-exported-from-audacity.txt)

**Comment by sebastiangelotte** [comment]
Automatically add labels in Audacity based on silence: https://manual.audacityteam.org/man/silence_finder.html

**Comment by Alekzanther** [comment]
I believe this is fixed now.
